export const accordionsData = [
  {
    title: "ATLAS",
    items: [
      { localite: "Analamanga", financeur: "UN-HABITAT", statut: "RÉALISÉ" },
      { localite: "Vatovavy", financeur: "UN-HABITAT", statut: "EN COURS" },{ localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
  {
    title: "SAC",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "SAIC",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "SRAT",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "PUDI",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "PUDé",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "SAC",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "SAC",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
   {
    title: "SAC",
    items: [
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
      { localite: "Boeny", financeur: "AFD", statut: "EN PROJET" },
      { localite: "Diana", financeur: "AFD", statut: "RÉALISÉ" },
    ],
  },
];
